### ISSUE TITLE
Generates a nullable as an object

### ISSUE THREAD

**Issue by cws-alb** [dart-ogurets/dart-openapi-maven#28] opened 2021-04-02 09:05 UTC
when using:

```
...
        <groupId>org.openapitools</groupId>
        <artifactId>openapi-generator-maven-plugin</artifactId>
        <version>5.1.0</version>
...
          <dependency>
            <groupId>com.bluetrainsoftware.maven</groupId>
            <artifactId>openapi-dart-generator</artifactId>
            <version>5.0</version>
          </dependency>
...
                <additionalProperty>nullSafe</additionalProperty>
```

When attempting to run the flutter, we are seeing a generated error similar to:

```
/<generated-code>/lib/api/user_api.dart:268:23: Error: A value of type 'UserSharePermissions?' can't be assigned to a variable of type 'Object' because 'UserSharePermissions?' is nullable and 'Object' isn't.
 - 'UserSharePermissions' is from 'package:<generated-code>/api.dart' ('<generated-code>/lib/api.dart').
 - 'Object' is from 'dart:core'.
    Object postBody = userSharePermissions;
```

The generated code looks like, and our hack to see if this fixed it are:
```
     Future<ApiResponse>

   getGeneratedMethod({Options? options, UserSharePermissions? userSharePermissions }) async {

-    Object postBody = userSharePermissions;

+    var postBody = userSharePermissions;
```

flutter doctor -v

```
[√] Flutter (Channel stable, 2.0.3, on Microsoft Windows [Version 10.0.19042.867], locale en-GB)
    • Flutter version 2.0.3 at 
    • Framework revision 4d7946a68d (2 weeks ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at W:\tools\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_SDK_ROOT = 
    • Java binary at: 
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at 
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Android Studio
    • Android Studio at 
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir =
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (3 available)

• No issues found!

**Comment by rvowles** [comment] 2021-04-04 07:38
Right, so you have a POST with a non-required body is that correct? In these cases, the most useful thing is the version & additional properties you are using and the snippet of OpenAPI that reproduces it. If I can confirm that is the case, I can fix it and cut a new release...

**Comment by cws-alb** [comment] 2021-04-04 08:31
`openapi: 3.0.3`

```
  '/user/testGen':
    post:
      tags:
        - user
      summary: >-
        Test the code gen.
      description: ''
      operationId: getUsp
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserSharePermissions'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/base64Blob'
```

```
    UserSharePermissions:
      type: object
      additionalProperties: false
      properties:
        usp1:
          type: array
          items:
            $ref: '#/components/schemas/uspChoice'
          minItems: 0
          maxItems: 16
        usp2:
          type: array
          items:
            $ref: '#/components/schemas/uspShare'
          minItems: 0
          maxItems: 16
```

**Comment by rvowles** [comment] 2021-04-04 21:57
Somehow I missed running my test cases with null safe and there is a whole boat load of issues with additional properties as well. This is going to take me a little while to fix.

**Comment by cws-alb** [comment] 2021-04-05 01:42
If there’s anything I can do to help please let me know.

**Comment by rvowles** [comment] 2021-04-05 05:19
I've been working on it for much of today, its quite quite complicated.

**Comment by rvowles** [comment] 2021-04-06 20:36
I think I will pull out just this piece and do a release and continue working on the complex structure issues.

**Comment by cws-alb** [comment] 2021-04-06 21:04
Thanks. Appreciate all you are doing. 

Again, happy to help in anyway.

**Comment by rvowles** [comment] 2021-04-07 01:47
5.1 has been released with this specific release in it. I'll create another ticket with the other issues and rebase.

**Comment by cws-alb** [comment] 2021-04-07 07:01
Thanks. I really appreciate your efforts.

**Comment by cws-alb** [comment] 2021-04-07 17:12
in 5.1, the pubspec still builds against 4.0.0-prev3. 4.0.0 is now released:
e.g.
```
 environment:
   sdk: '>=2.12.0 <3.0.0'
 dependencies:
-  dio: '4.0.0-prev3'
+  dio: '4.0.0'
   openapi_dart_common: ^4.0.0-prev1
   collection: '^1.15.0'
 dev_dependencies:
```

**Comment by rvowles** [comment] 2021-04-07 19:55
Yes, I mention  this in issue #30 - does it affect you? are you building a library? the Openapi Dart Common is in prev1 as well because of this and I intend to release 5.2 and the next openapi_dart_common at the same time.

**Comment by cws-alb** [comment] 2021-04-07 20:00
Thanks Richard. 

No. Not building a library, but just about to release to prod so better to build against full releases. I have manually changed the oi spec for now so all good. Only mentioned it as a prompt rather than anything else. 

Good news on the common package being released too!

Thanks again.

**Closed as completed** 2021-04-12 07:30 UTC
