### ISSUE TITLE
Please support latest openapi_dart_common and dio

### ISSUE THREAD

**Issue by MagnusJohansson** [dart-ogurets/dart-openapi-maven#36] opened 2021-04-19 19:34 UTC
In a project using the latest Firebase libraries, this ("dart-openapi-maven") is incompatible because it limits and pins the `dio` and `openapi_dart_common` to older versions.  (<v4 ) Causing conflicts.

Please update dart-openapi-maven to work with latest Firebase (i.e. upgrade to dio v4.0.0 and openapi_dart_common v4.0.0

**Comment by rvowles** [comment] 2021-04-19 22:45
Please move to 5.2 and null safety and it is done already.

**Comment by MagnusJohansson** [comment] 2021-04-20 05:25
Ok, where can I find that?
Latest version on https://search.maven.org/search?q=a:openapi-dart-generator 
is v5.1

Latest version on this release page https://github.com/dart-ogurets/dart-openapi-maven/releases
is v5.1

**Comment by rvowles** [comment] 2021-04-20 10:04
Well there is a turn up! It must have failed to upload to Central. I have released it again and watched it with an eagle eye, so you should be able to find it in a couple of hours.

**Comment by MagnusJohansson** [comment] 2021-04-20 12:57
I just tested with v5.2.
It still uses the older dio and openapi_dart_common  packages  (non-nullsafe versions)

I was expecting them to be v4.0.0 

https://github.com/dart-ogurets/dart-openapi-maven/blob/d0beceae0e1b2325b0d86ad885f9d27c744c60f6/src/main/resources/dart2-v3template/pubspec.mustache#L24

**Comment by MagnusJohansson** [comment] 2021-04-20 13:40
Ok, never mind, found out I have to add  `--additional-properties=nullSafe=true`

However, the generated .copyWith() methods seems a bit broken:
![image](https://user-images.githubusercontent.com/674909/115405533-9cce8280-a1ee-11eb-8fef-c66f78145c9b.png)

Have to manually change to `data?.`.

**Comment by rvowles** [comment] 2021-05-09 08:33
Duplicate of #37

**Closed as completed by rvowles** 2021-05-09 08:33 UTC
